### ISSUE TITLE
Need a way to rerender or refetch result of promise

### ISSUE THREAD

**Issue by swillis12** [erictooth/react-promise-switch#1]
For example:

1. Promise fetches a list of items.
2. User deletes an item from the list.
3. Need to refetch the list of items.

**Comment by erictooth** [comment]
Although the promise _can_ be re-triggered by passing a function with a different reference to the `promise` prop, I see that it can be messy to implement if you have to force the parent to re-render (when your promise result isn't necessarily derived from parent component state) just because you need to re-render `ReactPromiseSwitch`.

Added `refresh` prop in https://github.com/erictooth/react-promise-switch/commit/0472b7aae9bb902e8f5c0380f09e45efe0ecd22d and published as v1.2.0.
